// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthLevel int32

const (
	AuthLevel_level0 AuthLevel = 0
	AuthLevel_level2 AuthLevel = 1
	AuthLevel_level3 AuthLevel = 2
	AuthLevel_level4 AuthLevel = 3
)

var AuthLevel_name = map[int32]string{
	0: "level0",
	1: "level2",
	2: "level3",
	3: "level4",
}

var AuthLevel_value = map[string]int32{
	"level0": 0,
	"level2": 1,
	"level3": 2,
	"level4": 3,
}

func (x AuthLevel) String() string {
	return proto.EnumName(AuthLevel_name, int32(x))
}

func (AuthLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type UserDetails struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Name of the user
	FirstName            string    `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string    `protobuf:"bytes,3,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName             string    `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	LevelOfAuth          AuthLevel `protobuf:"varint,5,opt,name=levelOfAuth,proto3,enum=main.AuthLevel" json:"levelOfAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserDetails) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserDetails) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *UserDetails) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserDetails) GetLevelOfAuth() AuthLevel {
	if m != nil {
		return m.LevelOfAuth
	}
	return AuthLevel_level0
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type NewUserRequest struct {
	User                 *UserDetails `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string       `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetUser() *UserDetails {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type NewUserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NewUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VerifyRequest struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AuthLevelRequested   AuthLevel `protobuf:"varint,3,opt,name=authLevelRequested,proto3,enum=main.AuthLevel" json:"authLevelRequested,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyRequest) GetAuthLevelRequested() AuthLevel {
	if m != nil {
		return m.AuthLevelRequested
	}
	return AuthLevel_level0
}

type VerifyResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Granted              bool     `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *VerifyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyResponse) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

func init() {
	proto.RegisterEnum("main.AuthLevel", AuthLevel_name, AuthLevel_value)
	proto.RegisterType((*UserDetails)(nil), "main.UserDetails")
	proto.RegisterType((*LoginRequest)(nil), "main.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "main.LoginResponse")
	proto.RegisterType((*NewUserRequest)(nil), "main.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "main.NewUserResponse")
	proto.RegisterType((*VerifyRequest)(nil), "main.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "main.VerifyResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0x36, 0xdb, 0xfd, 0x95, 0xb7, 0x76, 0x1b, 0xc7, 0xad, 0x84, 0x20, 0x52, 0x02, 0x42, 0xf1,
	0xb0, 0x68, 0x5a, 0xf4, 0xe0, 0x41, 0x44, 0xf1, 0x54, 0x2a, 0xa4, 0xa8, 0x17, 0x2f, 0x63, 0xf3,
	0x76, 0x3b, 0x98, 0x4c, 0xd6, 0x99, 0x49, 0x8b, 0x57, 0xff, 0x28, 0x8f, 0xfe, 0x6d, 0x32, 0x3f,
	0x32, 0x26, 0x52, 0x96, 0xb2, 0xb7, 0xf9, 0xde, 0x9b, 0xf7, 0xe5, 0xfb, 0xbe, 0x37, 0x01, 0xa0,
	0x8d, 0xba, 0x5a, 0x6e, 0x44, 0xad, 0x6a, 0x32, 0xac, 0x28, 0xe3, 0xe9, 0xef, 0x00, 0x66, 0x9f,
	0x24, 0x8a, 0xf7, 0xa8, 0x28, 0x2b, 0x25, 0x49, 0x60, 0xda, 0x48, 0x14, 0x9c, 0x56, 0x18, 0x07,
	0x47, 0xc1, 0x71, 0x98, 0x7b, 0x4c, 0x1e, 0x43, 0xb8, 0x62, 0x42, 0xaa, 0x73, 0xdd, 0x1c, 0x98,
	0xe6, 0xbf, 0x02, 0x79, 0x02, 0x50, 0xb1, 0xa2, 0x28, 0xd1, 0xb4, 0xf7, 0x4c, 0xbb, 0x53, 0xd1,
	0xcc, 0x25, 0x75, 0xc3, 0x43, 0xcb, 0xdc, 0x62, 0xf2, 0x02, 0x66, 0x25, 0x5e, 0x63, 0xf9, 0x71,
	0xf5, 0xb6, 0x51, 0x57, 0xf1, 0xe8, 0x28, 0x38, 0x9e, 0x67, 0x07, 0x4b, 0xad, 0x70, 0xa9, 0x2b,
	0x67, 0xba, 0x99, 0x77, 0xef, 0xa4, 0x1f, 0xe0, 0xfe, 0x59, 0xbd, 0x66, 0x3c, 0xc7, 0x1f, 0x0d,
	0x4a, 0xb5, 0x55, 0x78, 0x02, 0xd3, 0x0d, 0x95, 0xf2, 0xa6, 0x16, 0x85, 0xd3, 0xed, 0x71, 0xfa,
	0x05, 0xf6, 0x1d, 0x8f, 0xdc, 0xd4, 0x5c, 0x22, 0x79, 0x04, 0x63, 0xa9, 0xa8, 0x6a, 0xa4, 0xa1,
	0x19, 0xe5, 0x0e, 0x91, 0x18, 0x26, 0x15, 0x4a, 0x49, 0xd7, 0xad, 0xf7, 0x16, 0x92, 0x05, 0x8c,
	0x54, 0xfd, 0x1d, 0xb9, 0x33, 0x6d, 0x41, 0x7a, 0x01, 0xf3, 0x73, 0xbc, 0xd1, 0xd9, 0xb6, 0x12,
	0x9f, 0xc2, 0x50, 0x4b, 0x32, 0xbc, 0xb3, 0xec, 0x81, 0xb5, 0xd7, 0x09, 0x3f, 0x37, 0xed, 0xad,
	0x6a, 0xdf, 0xc1, 0x81, 0x27, 0xdd, 0x55, 0x6f, 0xfa, 0x2b, 0x80, 0xfd, 0xcf, 0x28, 0xd8, 0xea,
	0xe7, 0x5d, 0xc2, 0xf3, 0xee, 0x06, 0x1d, 0x77, 0xe4, 0x0d, 0x10, 0xea, 0x17, 0x63, 0x59, 0xb0,
	0x30, 0x01, 0xdc, 0xb2, 0xb8, 0x5b, 0xae, 0xa6, 0x5f, 0x61, 0xde, 0x6a, 0xd8, 0x39, 0xf8, 0x18,
	0x26, 0x6b, 0x41, 0x79, 0xfb, 0xe5, 0x69, 0xde, 0xc2, 0x67, 0xaf, 0x21, 0xf4, 0x9f, 0x27, 0x00,
	0x63, 0xf3, 0x72, 0x9e, 0x47, 0xf7, 0xfc, 0x39, 0x8b, 0x02, 0x7f, 0x3e, 0x89, 0x06, 0xfe, 0x7c,
	0x1a, 0xed, 0x65, 0x7f, 0x02, 0x38, 0xd4, 0xd3, 0xc8, 0x15, 0xbb, 0xa4, 0x8a, 0xd5, 0xfc, 0x02,
	0xc5, 0x35, 0xbb, 0x44, 0xf2, 0x12, 0x26, 0x2e, 0x7e, 0xb2, 0xb0, 0x26, 0xfb, 0x2b, 0x4e, 0x0e,
	0xff, 0xab, 0x3a, 0x6b, 0xa7, 0x10, 0x9a, 0x47, 0x66, 0x26, 0x89, 0xbd, 0xd3, 0x7d, 0xbd, 0xc9,
	0xc3, 0x5e, 0xcd, 0x4d, 0xbd, 0x02, 0xb0, 0x11, 0x99, 0x31, 0x77, 0xa5, 0xb7, 0xb8, 0x64, 0xd1,
	0x2f, 0xda, 0xc1, 0x6f, 0x63, 0xf3, 0x87, 0x9f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x88, 0xe6,
	0x1c, 0x9b, 0xef, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	VerifyUser(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, "/main.AuthenticationService/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/main.AuthenticationService/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) VerifyUser(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/main.AuthenticationService/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	NewUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	VerifyUser(context.Context, *VerifyRequest) (*VerifyResponse, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) NewUser(ctx context.Context, req *NewUserRequest) (*NewUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUser not implemented")
}
func (*UnimplementedAuthenticationServiceServer) LoginUser(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedAuthenticationServiceServer) VerifyUser(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AuthenticationService/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).NewUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AuthenticationService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AuthenticationService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).VerifyUser(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _AuthenticationService_NewUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AuthenticationService_LoginUser_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _AuthenticationService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
